version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    ports:
      - 9200:9200
      - 9300:9300

  app:
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
    build:
      context: hangman-service
    ports:
      - 8080:8080
    depends_on:
      - elasticsearch

